services:
  employee:
    image: "pos/employee:v1"
    container_name: employee_pos
    ports:
      - "8080:8080"
    secrets:
      - pw_employee
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - posnet
  outlet:
    image: "pos/outlet:v1"
    container_name: outlet_pos
    ports:
      - "8081:8081"
    secrets:
      - pw_outlet
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - posnet

networks:
  posnet:
    driver: "bridge"

secrets:
  pw_employee:
    file: ./pw_employee.txt
  pw_outlet:
    file: ../outlet/pw_outlet.txt