services:
  employee:
    image: "pos/employee:v1"
    container_name: employee_pos
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - posnet
  outlet:
    image: "pos/outlet:v1"
    container_name: outlet_pos
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - posnet

networks:
  posnet:
    driver: "bridge"