global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'employee'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['employee:8080']
  - job_name: 'outlet'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['outlet:8081']
  - job_name: 'posserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['posserver:8082']
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8083']
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gatewayserver:8084']