services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yaml
      service: network-deploy-service

  posserver:
    image: "pos/posserver:v1"
    container_name: posserver-ms
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eureka:
    image: "pos/eurekaserver:v1"
    container_name: eurekaserver-ms
    ports:
      - "8083:8083"
    depends_on:
      posserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eureka"

  employee:
    image: "pos/employee:v1"
    container_name: employee-ms
    ports:
      - "8080:8080"
    depends_on:
      posserver:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "employee"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  outlet:
    image: "pos/outlet:v1"
    container_name: outlet-ms
    ports:
      - "8081:8081"
    depends_on:
      posserver:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "outlet"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  gatewayserver:
    image: "pos/gatewayserver:v1"
    container_name: gatewayserver-ms
    ports:
      - "8084:8084"
    depends_on:
      employee:
        condition: service_healthy
      outlet:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

networks:
  pos:
    driver: "bridge"